version: '3.8'

services:
  ollama:
    build:
      context: ./AI
      dockerfile: Dockerfile
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=http://0.0.0.0:11434
    restart: unless-stopped