version: "3.8"

services:
  gradio-chat-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PYTHONUNBUFFERED=1  # Direktes Loggen in Docker
    restart: unless-stopped
